language: go

go: 1.11

branches:
  except:
    - /^*-[0-9]/

# sudo: required

# install:
#   - make tools
#   - make deps.install
#   - make generate

before_script:
  - "if [ $TRAVIS_PULL_REQUEST = 'false' ]; then git checkout -qf $TRAVIS_BRANCH; fi"

script:
  - go build

# if this isnt a PR, and we're building the master branch *only*, then lets tag
# this version which will in turn trigger another build that the github release
# will be cut from.
# after_success:
# - |
#   if [ $TRAVIS_PULL_REQUEST = 'false' ]; then
#     if [ $TRAVIS_BRANCH = 'master' ]; then
#       git config --global user.email "builds@travis-ci.com"
#       git config --global user.name "Travis CI"
#       git tag ${CLI_VERSION} -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
#       git push -q https://$GIT_CREDENTIAL@github.com/getnelson/slipway --tags
#     fi
#   fi
